name:                template
version:             0.1.0.0
github:              "t4ccer/template"
license:             GPL-3-or-later
author:              "t4ccer"
maintainer:          "t4ccre@gmail.com"
copyright:           "t4ccer"

extra-source-files:
- README.org

description:         Please see the README on GitHub at <https://github.com/t4ccer/template#readme>

dependencies:
- base >= 4.10.0 && < 5

default-extensions:
  - NoStarIsType
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - GADTSyntax
  - GeneralisedNewtypeDeriving
  - HexFloatLiterals
  - ImplicitPrelude
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonomorphismRestriction
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - PostfixOperators
  - QualifiedDo
  - RankNTypes
  - RelaxedPolyRec
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances
  - ViewPatterns

library:
  source-dirs: src
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wno-unused-do-bind
    - -Wno-partial-type-signatures
    - -Wmissing-export-lists
    - -Wincomplete-record-updates
    - -Wmissing-deriving-strategies
    - -Wno-name-shadowing
    - -Wunused-foralls
    - -fprint-explicit-foralls
    - -fprint-explicit-kinds
    - -Wunused-do-bind
    - -Werror
  dependencies:
    - base
    - bytestring
    - containers
    - directory
    - filepath
    - mtl
    - text
    - transformers
    - vector
    
executables:
  template:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wno-unused-do-bind
    - -Wno-partial-type-signatures
    - -Wmissing-export-lists
    - -Wincomplete-record-updates
    - -Wmissing-deriving-strategies
    - -Wno-name-shadowing
    - -Wunused-foralls
    - -fprint-explicit-foralls
    - -fprint-explicit-kinds
    - -Wunused-do-bind

